yarnPath: .yarn/releases/yarn-3.1.1.cjs
nodeLinker: "pnp"
packageExtensions:
  "@storybook/core@*":
    peerDependencies:
      "@babel/core": "*"
  "corejs-upgrade-webpack-plugin@*":
    dependencies:
      babel-runtime: ^6.26.0
